# -*- coding: utf-8 -*-
"""cyber_risk_integrated_agent_pipeline (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_gJCKwz6jupJuutL-WIuWhcevcqNTtE1

# Cyber Risk Integrated Agent - Complete Pipeline
This notebook builds an end-to-end cyber insurance underwriting and risk quotation agent. It processes historical incident data, trains frequency and severity models, extracts the actuarial coefficients dynamically, and sets up an Agentic AI system using Agno and Gemini to generate custom coverage quotes.

### Module Imports & Initial Configuration
"""

import os
import sys
import json
import numpy as np
import pandas as pd
import warnings
from typing import Dict, Tuple, Any
from datetime import datetime
import subprocess
import streamlit as st

warnings.filterwarnings("ignore")

# if "GOOGLE_API_KEY" in st.secrets:
#     os.environ["GOOGLE_API_KEY"] = st.secrets["GOOGLE_API_KEY"]
# else:
#     st.error("ERROR: GOOGLE_API_KEY not found in Streamlit Secrets. Please set it in .streamlit/secrets.toml")

# if "GOOGLE_API_KEY" not in os.environ:
#     if "GOOGLE_API_KEY" in st.secrets:
#         os.environ["GOOGLE_API_KEY"] = st.secrets["GOOGLE_API_KEY"]
#     elif "Final_Project_Key" in st.secrets:
#         os.environ["GOOGLE_API_KEY"] = st.secrets["Final_Project_Key"]
#     else:
#         st.error("ERROR: GOOGLE_API_KEY not found in Streamlit Secrets. Please set it in .streamlit/secrets.toml")
# else:
#     st.error("ERROR: GOOGLE_API_KEY not found in Streamlit Secrets. Please set it in .streamlit/secrets.toml")

print("=" * 80)
print("INTEGRATED CYBER RISK QUOTATION AGENT - COMPLETE PIPELINE")
print("=" * 80)

## PHASE 0

print("\n[PHASE 0] Installing dependencies...")
# !pip install -q agno google-genai scipy scikit-learn pandas numpy matplotlib

from agno.agent import Agent
from agno.models.google import Gemini
from scipy import stats
from sklearn.linear_model import Ridge, PoissonRegressor
from sklearn.model_selection import train_test_split

print("✓ Dependencies installed")

## PHASE 1

print("\n[PHASE 1] Loading incident data from CSV files...")

try:
    # incidents = pd.read_csv(
    #     r"C:\Users\Rajat\Desktop\rajat\actuarials\AI Internship Program\Project\Cyber Risk Data\incidents_master_cleaned.csv"
    # )
    # financial = pd.read_csv(
    #     r"C:\Users\Rajat\Desktop\rajat\actuarials\AI Internship Program\Project\Cyber Risk Data\financial_impact_cleaned.csv"
    # )
    # market = pd.read_csv(
    #     r"C:\Users\Rajat\Desktop\rajat\actuarials\AI Internship Program\Project\Cyber Risk Data\market_impact_cleaned.csv"
    # )

    # incidents = pd.read_csv( "/content/data/incidents_master_cleaned.csv")
    # financial = pd.read_csv( "/content/data/financial_impact_cleaned.csv")
    # market = pd.read_csv( "/content/data/market_impact_cleaned.csv")

    incidents = pd.read_csv( "https://raw.githubusercontent.com/rajat4186/Cyber-Risk-Premium-Pricing-Agentic-AI-Project/refs/heads/main/data/incidents_master_cleaned.csv")
    financial = pd.read_csv( "https://raw.githubusercontent.com/rajat4186/Cyber-Risk-Premium-Pricing-Agentic-AI-Project/refs/heads/main/data/financial_impact_cleaned.csv")
    market = pd.read_csv( "https://raw.githubusercontent.com/rajat4186/Cyber-Risk-Premium-Pricing-Agentic-AI-Project/refs/heads/main/data/market_impact_cleaned.csv")

    
    print(f"✓ Loaded incidents: {len(incidents)} records")
    print(f"✓ Loaded financial: {len(financial)} records")
    print(f"✓ Loaded market: {len(market)} records")

    print("✓ Data cleaned and ready")
    DATA_AVAILABLE = True

except Exception as e:
    print(f"⚠️  Data loading error: {e}")
    print("⚠️  Will use pre-defined coefficients as fallback")
    DATA_AVAILABLE = False
    incidents = None
    financial = None

## PHASE 1.5

print("\n[PHASE 1.5] Training Poisson GLM Frequency Model...")

def train_frequency_model(incidents_df):
    """
    Train Poisson GLM frequency model and return coefficients
    """
    try:
        # Aggregate incidents by company
        company_freq = (
            incidents_df.groupby("company_name")
            .agg(
                {
                    "incident_id": "count",
                    "company_revenue_usd": "first",
                    "employee_count": "first",
                    "is_public_company": "first",
                }
            )
            .reset_index()
        )

        company_freq.rename(columns={"incident_id": "incident_count"}, inplace=True)
        company_freq = company_freq.dropna()

        print(f"  • Aggregated {len(company_freq)} companies from incidents")

        # Feature engineering
        X_freq = company_freq[
            ["company_revenue_usd", "employee_count", "is_public_company"]
        ].copy()
        y_freq = company_freq["incident_count"].copy()

        X_freq["log_revenue"] = np.log1p(X_freq["company_revenue_usd"])
        X_freq["log_employees"] = np.log1p(X_freq["employee_count"])

        # Company size category
        X_freq["revenue_tier"] = pd.cut(
            X_freq["company_revenue_usd"],
            bins=[0, 1e9, 10e9, 100e9, np.inf],
            labels=[0, 1, 2, 3],
        ).astype(int)

        feature_cols = [
            "log_revenue",
            "log_employees",
            "is_public_company",
            "revenue_tier",
        ]
        X_freq_model = X_freq[feature_cols].fillna(0)

        # Train-test split
        X_train, X_test, y_train, y_test = train_test_split(
            X_freq_model, y_freq, test_size=0.2, random_state=42
        )

        print(f"  • Train: {len(X_train)}, Test: {len(X_test)}")

        # Train Poisson model with Ridge regularization
        freq_model = PoissonRegressor(alpha=0.1292, max_iter=1000)
        freq_model.fit(X_train, y_train)

        # Extract coefficients
        coefficients = {
            "intercept": float(freq_model.intercept_),
            "log_revenue": float(freq_model.coef_[0]),
            "log_employees": float(freq_model.coef_[1]),
            "is_public": float(freq_model.coef_[2]),
            # "revenue_tier": float(freq_model.coef_[3]),
        }

        # Performance metrics
        train_score = freq_model.score(X_train, y_train)
        test_score = freq_model.score(X_test, y_test)

        print(f"✓ Frequency Model Trained")
        print(f"  • Training R²: {train_score:.4f}")
        print(f"  • Testing R²: {test_score:.4f}")
        print(f"  • Intercept: {coefficients['intercept']:.4f}")

        return coefficients

    except Exception as e:
        print(f"⚠️  Error training frequency model: {e}")
        return None

# Run frequency model training
if DATA_AVAILABLE and incidents is not None:
    FREQ_COEFFICIENTS = train_frequency_model(incidents)
else:
    raise Exception("Frequency model training failed")

## PHASE 2

print("\n[PHASE 2] Training Lognormal Severity Model...")

def train_severity_model(incidents_df, financial_df):
    """
    Train Lognormal severity model and return coefficients + parameters
    """
    try:
        losses = financial_df["total_loss_usd"].values
        log_losses = np.log(losses)

        # Lognormal parameters
        mu = float(log_losses.mean())
        sigma = float(log_losses.std())

        print(f"  • Loss records: {len(losses)}")
        print(f"  • Mean loss: ${np.mean(losses) / 1e6:.1f}M")
        print(f"  • Lognormal: μ={mu:.4f}, σ={sigma:.4f}")

        # Train severity regression model
        merged = incidents_df.merge(financial_df, on="incident_id", how="inner")

        if len(merged) == 0:
            raise Exception("No merged data between incidents and financial")

        print(f"  • Merged records: {len(merged)}")

        # Features
        X_sev = merged[
            ["company_revenue_usd", "employee_count", "is_public_company"]
        ].copy()
        X_sev["log_revenue"] = np.log1p(X_sev["company_revenue_usd"])
        X_sev["log_employees"] = np.log1p(X_sev["employee_count"])
        X_sev["log_records"] = np.log1p(1000000)  # Default records at risk

        feature_cols_sev = [
            "log_revenue",
            "log_employees",
            "is_public_company",
            "log_records",
        ]
        X_sev_model = X_sev[feature_cols_sev].fillna(0)
        y_sev = np.log(merged["total_loss_usd"])

        # Train-test split
        X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
            X_sev_model, y_sev, test_size=0.2, random_state=42
        )

        # Train Ridge regression on log scale
        sev_model = Ridge(alpha=1.0)
        sev_model.fit(X_train_s, y_train_s)

        # Extract coefficients
        coefficients = {
            "intercept": float(sev_model.intercept_),
            "log_revenue": float(sev_model.coef_[0]),
            "log_employees": float(sev_model.coef_[1]),
            "is_public": float(sev_model.coef_[2]),
            "log_records": float(sev_model.coef_[3]),
        }

        # Performance
        test_score = sev_model.score(X_test_s, y_test_s)

        print(f"✓ Severity Model Trained")
        print(f"  • Testing R²: {test_score:.4f}")
        print(f"  • Intercept: {coefficients['intercept']:.4f}")

        lognorm_params = {"mu": mu, "sigma": sigma}

        return coefficients, lognorm_params

    except Exception as e:
        print(f"⚠️  Error training severity model: {e}")
        return None, None

# Run severity model training
if DATA_AVAILABLE and incidents is not None and financial is not None:
    SEVER_COEFFICIENTS, LOGNORM_PARAMS = train_severity_model(incidents, financial)
else:
    raise Exception("Severity model training failed")

## PHASE 3

print("\n[PHASE 3] Initializing quotation system with extracted coefficients...")

LOADING_FACTORS = {
    "acquisition": 0.20,
    "admin": 0.10,
    "profit": 0.15,
    "uncertainty": 0.08,
    "reinsurance": 0.05,
}

TOTAL_LOADING = sum(LOADING_FACTORS.values())
LOADING_MULTIPLIER = 1 + TOTAL_LOADING

INDUSTRY_RELATIVITIES = {
    "51": 1.231,
    "52": 1.181,
    "44-45": 1.264,
    "92": 1.221,
    "31-33": 1.023,
    "21": 0.955,
    "62": 0.914,
    "22": 0.885,
    "42": 0.804,
    "55": 1.417,
}

REVENUE_TIER_RANGES = {
    "Q1_Small": (0, 1e9),
    "Q2_Medium": (1e9, 10e9),
    "Q3_Large": (10e9, 100e9),
    "Q4_Enterprise": (100e9, float("inf")),
}

# REVENUE_TIER_RELATIVITIES = {
#     "Q1_Small": 0.346,
#     "Q2_Medium": 0.578,
#     "Q3_Large": 1.024,
#     "Q4_Enterprise": 2.050,
# }

INDUSTRY_CODES = {
    "21": "Mining",
    "22": "Utilities",
    "31-33": "Industrial Manufacturing",
    "42": "Business Services",
    "44-45": "Retail",
    "51": "Technology",
    "52": "Finance & Insurance",
    "55": "Specialty",
    "62": "IT Services",
    "92": "Telecom",
}

print(f"✓ Coefficients extracted and loaded:")
print(f"  • Frequency coefficients: {list(FREQ_COEFFICIENTS.keys())}")
print(f"  • Severity coefficients: {list(SEVER_COEFFICIENTS.keys())}")
print(f"  • Lognormal parameters: μ={LOGNORM_PARAMS['mu']:.4f}, σ={LOGNORM_PARAMS['sigma']:.4f}")
print(f"  • Loading factors: {TOTAL_LOADING * 100:.1f}%")

print("\n[PHASE 3.5] Defining prediction functions with EXTRACTED coefficients...")

def predict_frequency(
    company_revenue: float, employee_count: int, is_public: bool
) -> dict:
    """Predict frequency using Poisson GLM with EXTRACTED coefficients from trained model"""
    log_revenue = np.log1p(company_revenue)
    log_employees = np.log1p(employee_count)
    is_public_numeric = 1 if is_public else 0

    if company_revenue < 1e9:
        size_category = 0
    elif company_revenue < 10e9:
        size_category = 1
    elif company_revenue < 100e9:
        size_category = 2
    else:
        size_category = 3

    # Use EXTRACTED coefficients
    log_lambda = (
        FREQ_COEFFICIENTS["intercept"]
        + FREQ_COEFFICIENTS["log_revenue"] * log_revenue
        + FREQ_COEFFICIENTS["log_employees"] * log_employees
        + FREQ_COEFFICIENTS["is_public"] * is_public_numeric
        # + FREQ_COEFFICIENTS["revenue_tier"] * size_category
    )

    predicted_frequency = np.exp(log_lambda)
    risk_score = (predicted_frequency / 1.1354) * 100

    return {
        "predicted_frequency": round(predicted_frequency, 4),
        "risk_score": round(risk_score, 1),
        "size_category": ["Small", "Medium", "Large", "Enterprise"][size_category],
    }

def predict_severity(
    company_revenue: float,
    employee_count: int,
    is_public: bool,
    records_at_risk: int = 1000000,
) -> dict:
    """Predict severity using Lognormal with EXTRACTED coefficients from trained model"""
    log_revenue = np.log1p(company_revenue)
    log_employees = np.log1p(employee_count)
    is_public_numeric = 1 if is_public else 0
    log_records = np.log1p(records_at_risk)

    # Use EXTRACTED coefficients
    log_loss = (
        SEVER_COEFFICIENTS["intercept"]
        + SEVER_COEFFICIENTS["log_revenue"] * log_revenue
        + SEVER_COEFFICIENTS["log_employees"] * log_employees
        + SEVER_COEFFICIENTS["is_public"] * is_public_numeric
        + SEVER_COEFFICIENTS["log_records"] * log_records
    )

    expected_loss = np.exp(log_loss)

    # Use EXTRACTED lognormal parameters
    q95_loss = np.exp(LOGNORM_PARAMS["mu"] + LOGNORM_PARAMS["sigma"] * 1.6449)

    return {
        "expected_severity": round(expected_loss, 0),
        "q95_loss": round(q95_loss, 0),
    }

def get_industry_relativity(industry_code: str) -> float:
    return INDUSTRY_RELATIVITIES.get(industry_code, 1.0)

# def get_revenue_tier_relativity(company_revenue: float) -> tuple:
#     for tier, (min_rev, max_rev) in REVENUE_TIER_RANGES.items():
#         if min_rev <= company_revenue < max_rev:
#             return tier, REVENUE_TIER_RELATIVITIES[tier]
#     return "Unknown", 1.0

def calculate_pure_premium(frequency: float, severity: float, company_revenue: float) -> dict:
    pure_premium = frequency * severity
    loading_dict = {
        "acquisition": pure_premium * LOADING_FACTORS["acquisition"],
        "admin": pure_premium * LOADING_FACTORS["admin"],
        "profit": pure_premium * LOADING_FACTORS["profit"],
        "uncertainty": pure_premium * LOADING_FACTORS["uncertainty"],
        "reinsurance": pure_premium * LOADING_FACTORS["reinsurance"],
    }
    total_loading = sum(loading_dict.values())
    final_premium = pure_premium + total_loading
    company_revenue = merged["company_revenue_usd"]
    
    # Defining the upper bound guardrail (max 5% of company revenue)
    max_allowable_premium = company_revenue * 0.05 
    is_capped = final_premium > max_allowable_premium
    if is_capped:
        # final_premium = max_allowable_premium
        reduction_factor = max_allowable_premium / final_premium
        pure_premium *= reduction_factor
        total_loading *= reduction_factor
        final_premium = max_allowable_premium
        loading_dict = {k: v * reduction_factor for k, v in loading_dict.items()}
        
    return {
        "pure_premium": round(pure_premium, 0),
        "loading_components": {k: round(v, 0) for k, v in loading_dict.items()},
        "total_loading": round(total_loading, 0),
        "final_premium": round(final_premium, 0),
    }

def generate_coverage_tiers(final_premium: float) -> dict:
    tier1_premium = final_premium * 1.00
    tier2_premium = final_premium * 0.6
    combined_premium = tier1_premium + tier2_premium

    return {
        "tier1": {"premium": round(tier1_premium, 0)},
        "tier2": {"premium": round(tier2_premium, 0)},
        "combined": {"premium": round(combined_premium, 0)},
    }

print("✓ Prediction functions defined with EXTRACTED coefficients")

## PHASE 4

print("\n[PHASE 4] Defining agent tools...")

def premium_quotation_tool(
    company_name: str,
    company_revenue_usd: float,
    employee_count: int,
    industry_code: str,
    is_public_company: bool,
    data_records_at_risk: int = 1000000,
) -> str:
    """Generate premium quote using extracted model coefficients"""
    try:
        freq_result = predict_frequency(
            company_revenue_usd, employee_count, is_public_company
        )
        frequency = freq_result["predicted_frequency"]

        sev_result = predict_severity(
            company_revenue_usd, employee_count, is_public_company, data_records_at_risk
        )
        severity = sev_result["expected_severity"]

        industry_rel = get_industry_relativity(industry_code)
        # revenue_tier, revenue_rel = get_revenue_tier_relativity(company_revenue_usd)

        premium_calc = calculate_pure_premium(frequency, severity, company_revenue_usd)
        base_final_premium = premium_calc["final_premium"]
        adjusted_premium = base_final_premium * industry_rel # * revenue_rel
        coverage_tiers = generate_coverage_tiers(adjusted_premium)

        quotation = {
            "quotation_id": f"QUOTE-{datetime.now().strftime('%Y%m%d%H%M%S')}",
            "company": {
                "name": company_name,
                "revenue_billions": round(company_revenue_usd / 1e9, 1),
                "employees": employee_count,
                "industry": INDUSTRY_CODES.get(industry_code, "Unknown"),
                "status": "Public" if is_public_company else "Private",
            },
            "actuarial_metrics": {
                "predicted_frequency_EXTRACTED": frequency,
                "risk_score": freq_result["risk_score"],
                "expected_severity_EXTRACTED": f"${severity:,.0f}",
                "pure_premium": f"${premium_calc['pure_premium']:,.0f}",
            },
            "adjustments": {
                "base_final_premium": f"${base_final_premium:,.0f}",
                "industry_adjustment_factor": f"{industry_rel:.3f}x",
                # "revenue_tier_adjustment_factor": f"{revenue_rel:.3f}x",
                "final_adjusted_premium": f"${adjusted_premium:,.0f}",
            },
            "loading_breakdown_58percent": {
                "acquisition_20pct": f"${premium_calc['loading_components']['acquisition']:,.0f}",
                "admin_10pct": f"${premium_calc['loading_components']['admin']:,.0f}",
                "profit_15pct": f"${premium_calc['loading_components']['profit']:,.0f}",
                "uncertainty_8pct": f"${premium_calc['loading_components']['uncertainty']:,.0f}",
                "reinsurance_5pct": f"${premium_calc['loading_components']['reinsurance']:,.0f}",
                "total_loading": f"${premium_calc['total_loading']:,.0f}",
            },
            "coverage_tier_1_primary": {
                "name": "Primary Coverage (Tier 1)",
                "covers": ["Ransomware", "Data Breaches", "Supply Chain"],
                "annual_premium": f"${coverage_tiers['tier1']['premium']:,.0f}",
            },
            "coverage_tier_2_secondary": {
                "name": "Secondary Coverage (Tier 2)",
                "covers": ["DDoS", "Malware", "Trojans", "Backdoors", "APTs"],
                "annual_premium": f"${coverage_tiers['tier2']['premium']:,.0f}",
            },
            "coverage_combined": {
                "name": "Complete Coverage (Tier 1 + Tier 2)",
                "annual_premium": f"${coverage_tiers['combined']['premium']:,.0f}",
                "recommended_for": "Enterprise, Finance, Healthcare companies",
            },
        }

        return json.dumps(quotation, indent=2)
    except Exception as e:
        return json.dumps({"error": str(e)}, indent=2)

def explain_coverage_tiers(tier: int) -> str:
    """Explain what is covered in each tier"""
    tiers_info = {
        1: {
            "name": "Tier 1: Primary Coverage (100% of base premium)",
            "attack_vectors": ["Ransomware", "Data Breaches", "Supply Chain"],
            "includes": [
                "Incident response and forensics",
                "Data recovery and restoration",
                "Legal and regulatory defense",
                "Business interruption coverage",
                "Public relations and notification",
            ],
            "best_for": "All companies - baseline protection",
        },
        2: {
            "name": "Tier 2: Secondary Coverage (60% of base premium)",
            "attack_vectors": ["DDoS", "Malware", "Trojans", "Backdoors", "APTs"],
            "includes": [
                "Advanced threat monitoring",
                "Network resilience protection",
                "Cyber extortion response",
                "Regulatory fines and penalties",
                "Extended system restoration",
            ],
            "best_for": "Tech, Finance, Healthcare - comprehensive protection",
        },
    }
    if tier not in tiers_info:
        return json.dumps({"error": "Invalid tier (1 or 2)"}, indent=2)
    return json.dumps(tiers_info[tier], indent=2)

def compare_coverage_costs(tier1_premium: float) -> str:
    """Compare costs of different coverage options"""
    tier2_premium = tier1_premium * 0.6
    combined_premium = tier1_premium + tier2_premium

    comparison = {
        "tier_1_only": {
            "annual_cost": f"${tier1_premium:,.0f}",
            "covers": "Ransomware, Data Breaches, Supply Chain",
            "best_for": "Small/medium businesses",
        },
        "tier_2_only": {
            "annual_cost": f"${tier2_premium:,.0f}",
            "covers": "DDoS, Malware, Trojans, Backdoors, APTs",
            "best_for": "Tech-focused companies",
        },
        "tier_1_and_2_combined": {
            "annual_cost": f"${combined_premium:,.0f}",
            "covers": "All cyber threats (comprehensive)",
            "best_for": "Enterprise, Finance, Healthcare",
            "recommended": True,
        },
    }
    return json.dumps(comparison, indent=2)

print("✓ Agent tools defined")

## [PHASE 5] Create Agentic AI Quotation Agent
## Configure the Agno Agent object using Gemini 3.1 Flash Lite, providing instructions and attaching the actuarial underwriting rulesets.


print("\n[PHASE 5] Creating Agentic AI quotation agent...")

def create_quotation_agent() -> Agent:
    """Create agent with extracted model coefficients"""
    # tools = [
    #     {
    #         "name": "premium_quotation_tool",
    #         "description": "Generates complete cyber insurance premium quote using extracted frequency and severity model coefficients. Requires company name, revenue, employees, industry code, public status, and optional data records at risk.",
    #         "function": premium_quotation_tool,
    #     },
    #     {
    #         "name": "explain_coverage_tiers",
    #         "description": "Explains what is covered in Tier 1 (Primary: Ransomware, Data Breaches, Supply Chain) or Tier 2 (Secondary: DDoS, Malware, Trojans, Backdoors, APTs)",
    #         "function": explain_coverage_tiers,
    #     },
    #     {
    #         "name": "compare_coverage_costs",
    #         "description": "Compares annual costs of Tier 1 only, Tier 2 only, or combined Tier 1+2 coverage. Provide the Tier 1 annual premium amount.",
    #         "function": compare_coverage_costs,
    #     },
    # ]

    tools = [
        premium_quotation_tool,
        explain_coverage_tiers,
        compare_coverage_costs
    ]

    agent = Agent(
        name="Cyber Risk Premium Quotation Agent",
        model=Gemini(id="gemini-3.1-flash-lite"),
        tools=tools,
        instructions="""You are a professional cyber insurance underwriting agent using EXTRACTED coefficients from trained frequency and severity models.

MODELS USED:
- Frequency: Poisson GLM (coefficients extracted from trained model)
- Severity: Lognormal + Ridge regression (coefficients extracted from trained model)
- Loading: 58% industry-standard factors

COVERAGE TIERS:
- Tier 1 (Primary): Ransomware, Data Breaches, Supply Chain - 100% of base premium
- Tier 2 (Secondary): DDoS, Malware, Trojans, Backdoors, APTs - 60% of base premium

WORKFLOW:
1. Gather company information (name, revenue, employees, industry, public status)
2. Use premium_quotation_tool with all company details
3. Present Tier 1 and Tier 2 quotes
4. Recommend appropriate coverage based on company profile:
   - Small/Medium: Tier 1
   - Tech/Finance/Healthcare: Tier 1 + Tier 2 combined
   - Enterprise: Tier 1 + Tier 2 combined

IMPORTANT: All coefficients are EXTRACTED from trained models on real incident data.
Be professional, clear, and business-focused in your explanations.""",
        markdown=True,
    )
    return agent

quotation_agent = create_quotation_agent()
print("✓ Agentic AI agent created and ready")

## [PHASE 6] Pipeline Verification & Actuarial Summary
# Verify complete extraction accuracy across all pipeline steps and log out final risk factors.


print("\n" + "=" * 80)
print("✓ INTEGRATED PIPELINE COMPLETE AND READY")
print("=" * 80)

print(f"\n📊 MODELS SUMMARY (Using EXTRACTED Coefficients):")
print(f"\n  FREQUENCY MODEL:")
print(f"    Type: Poisson GLM with Ridge regularization")
print(f"    Intercept: {FREQ_COEFFICIENTS['intercept']:.4f}")
print(f"    Log Revenue coef: {FREQ_COEFFICIENTS['log_revenue']:.4f}")
print(f"    Log Employees coef: {FREQ_COEFFICIENTS['log_employees']:.4f}")
print(f"    Is Public coef: {FREQ_COEFFICIENTS['is_public']:.4f}")
# print(f"    Revenue Tier coef: {FREQ_COEFFICIENTS['revenue_tier']:.4f}")

print(f"\n  SEVERITY MODEL:")
print(f"    Type: Lognormal distribution + Ridge regression")
print(f"    Lognormal μ: {LOGNORM_PARAMS['mu']:.4f}")
print(f"    Lognormal σ: {LOGNORM_PARAMS['sigma']:.4f}")
print(f"    Regression Intercept: {SEVER_COEFFICIENTS['intercept']:.4f}")
print(f"    Log Revenue coef: {SEVER_COEFFICIENTS['log_revenue']:.4f}")

print(f"\n  PREMIUM ENGINE:")
print(f"    Loading Factors: {TOTAL_LOADING * 100:.1f}%")
print(f"    Industries: {len(INDUSTRY_RELATIVITIES)}")
# print(f"    Revenue Tiers: {len(REVENUE_TIER_RELATIVITIES)}")
print(f"    Coverage Tiers: Tier 1 (100%) + Tier 2 (60%)")

print(f"\n🚀 AGENT READY FOR QUERIES")
print(f"\nUsage:")
print(f"  quotation_agent.print_response('Your query here')")

## [BONUS] Local Risk Validation & Evaluation Testing
# Execute a comprehensive sanity test locally to verify standard premium calculation values prior to calling the LLM orchestrator.


print(f"\n[BONUS] Testing predictions with EXTRACTED coefficients locally...")

# Test case: Large tech company
print(f"\nTest Company Profile:")
print(f"  • Revenue: $150 billion")
print(f"  • Employees: 250,000")
print(f"  • Industry: Technology (51)")
print(f"  • Status: Public")
print(f"  • Data at risk: 100 million records")

# Predictions using EXTRACTED coefficients
test_freq = predict_frequency(150e9, 250000, True)
test_sev = predict_severity(150e9, 250000, True, 100e6)
test_premium = calculate_pure_premium(
    test_freq["predicted_frequency"], test_sev["expected_severity"], company_revenue
)
test_tiers = generate_coverage_tiers(test_premium["final_premium"])

# Industry and size adjustments
industry_rel = get_industry_relativity("51")
# revenue_tier, revenue_rel = get_revenue_tier_relativity(150e9)

adjusted_premium = test_premium["final_premium"] * industry_rel # * revenue_rel
final_tiers = generate_coverage_tiers(adjusted_premium)

print(f"\nPredictions using EXTRACTED Coefficients:")
print(f"  • Frequency (Poisson GLM): {test_freq['predicted_frequency']:.4f}")
print(f"  • Risk Score: {test_freq['risk_score']:.1f}")
print(f"  • Severity (Lognormal): ${test_sev['expected_severity']:,.0f}")
print(f"  • Pure Premium: ${test_premium['pure_premium']:,.0f}")
print(f"  • With Loading (58%): ${test_premium['final_premium']:,.0f}")

print(f"\nAdjustments:")
print(f"  • Industry (Tech 51): {industry_rel:.3f}x")
# print(f"  • Revenue Tier ({revenue_tier}): {revenue_rel:.3f}x")
print(f"  • Adjusted Premium: ${adjusted_premium:,.0f}")

print(f"\nCoverage Tiers:")
print(f"  • Tier 1 (Primary): ${final_tiers['tier1']['premium']:,.0f}/year")
print(f"  • Tier 2 (Secondary): ${final_tiers['tier2']['premium']:,.0f}/year")
print(
    f"  • Combined (Recommended): ${final_tiers['combined']['premium']:,.0f}/year"
)

print(f"\n✓ All functions working correctly with EXTRACTED coefficients!")

## [PHASE 7] Hosting App On Streamlit
 
# Configure Streamlit
st.set_page_config(
    page_title="Cyber & AI Risk Insurance Pricing",
    page_icon="🛡️",
    layout="wide"
)
 
st.title("🛡️ Cyber & AI Risk Insurance Pricing Engine")
st.markdown("""
Dynamic actuarial pricing using AI-powered Frequency-Severity models.
""")
 
# API Key Setup
# if "GOOGLE_API_KEY" not in os.environ:
#     if "GOOGLE_API_KEY" in st.secrets:
#         os.environ["GOOGLE_API_KEY"] = st.secrets["GOOGLE_API_KEY"]
#     elif "Final_Project_Key" in st.secrets:
#         os.environ["GOOGLE_API_KEY"] = st.secrets["Final_Project_Key"]
 
# Initialize Chat History (unique key for insurance agent)
if "insurance_agent_messages" not in st.session_state:
    st.session_state.insurance_agent_messages = [
        {
            "role": "assistant",
            "content": "Welcome to the Cyber Insurance Pricing Engine. Please provide your company details to generate a customized quote."
        }
    ]
 
# Display Chat History
for msg in st.session_state.insurance_agent_messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
 
# User Input
if user_query := st.chat_input("Describe your company or request a quote..."):
    st.session_state.insurance_agent_messages.append({"role": "user", "content": user_query})
    
    with st.chat_message("user"):
        st.markdown(user_query)
 
    with st.chat_message("assistant"):
        response_placeholder = st.empty()
        
        try:
            if quotation_agent is not None:
                agent_response = quotation_agent.run(user_query)
                output_text = agent_response.content if hasattr(agent_response, 'content') else str(agent_response)
            else:
                output_text = "Agent initialization pending. Please check API configuration."
            
            response_placeholder.markdown(output_text)
            st.session_state.insurance_agent_messages.append({"role": "assistant", "content": output_text})
            
        except Exception as e:
            error_msg = f"⚠️ Processing error: {str(e)}"
            response_placeholder.error(error_msg)
 
print("✓ Application ready for deployment")
