# -*- coding: utf-8 -*-
"""Cyber_AI_Reinsurance_Quotation_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlGKpqHZkAheXg6Pxcpse0v067wz7wy6

# Cyber & AI Risk Reinsurance Quotation Agent
## Agentic AI with Proportional & Excess of Loss Pricing

**Project:** Cyber & AI Risk Insurance Pricing (Actuarial)
**Framework:** Agno + Google Gemini
**Data Source:** complete_pricing_framework.xlsx (750 companies, 20 industries)
**Status:** Production Ready

## 1. Install Dependencies
"""

!pip install -q agno google-genai
print('✓ Dependencies installed')

"""## 2. Standard Imports & Configuration"""

import os
import json
import numpy as np
import pandas as pd
from typing import Any, Dict
from dataclasses import dataclass
from datetime import datetime
import time
from agno.agent import Agent
from agno.models.google import Gemini

np.random.seed(42)
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 120)

print('✓ Imports successful')

"""## 3. API Key Setup"""

try:
    from google.colab import userdata
    os.environ["GOOGLE_API_KEY"] = userdata.get("GEMINI_API_KEY")
except (ImportError, Exception):
    if "GOOGLE_API_KEY" not in os.environ:
        raise RuntimeError(
            "GOOGLE_API_KEY is not set. "
            "Add it via Colab Secrets (left sidebar key icon, name: GOOGLE_API_KEY) "
            "or export it as an environment variable."
        )

print("API key loaded.")

"""## 3. Actuarial Data & Model Parameters

From complete_pricing_framework.xlsx (750 companies analyzed)
"""

@dataclass
class ActuarialConstants:
    # Premium Statistics (from 750 companies)
    mean_pure_premium: float = 26.4  # $26.4M
    mean_final_premium: float = 41.8  # $41.8M
    median_final_premium: float = 30.7
    min_final_premium: float = 8.7
    max_final_premium: float = 163.5
    std_dev_premium: float = 30.0

    # Loading Factors (from Summary sheet)
    acquisition_expenses_pct: float = 0.20  # 20%
    admin_expenses_pct: float = 0.10  # 10%
    profit_margin_pct: float = 0.15  # 15%
    uncertainty_buffer_pct: float = 0.08  # 8%
    reinsurance_ceded_pct: float = 0.05  # 5%
    total_loading_pct: float = 0.58  # 58% total

    # Proportional Reinsurance
    quota_share_pct: float = 0.30
    quota_share_commission: float = 0.30
    surplus_share_pct: float = 0.15
    surplus_commission: float = 0.30

    # XOL Parameters
    xol_profit_loading: float = 1.50

ACTUARIAL = ActuarialConstants()
print('✓ Actuarial constants loaded from complete_pricing_framework.xlsx')

"""## 4. Industry Classification & Risk Multipliers

20 industries from complete_pricing_framework.xlsx (Industry Summary sheet)
"""

# Industry Data from complete_pricing_framework.xlsx (Industry Summary sheet)
INDUSTRY_DATA = {
    '55': {'name': 'Management of Companies', 'relativity': 1.417, 'count': 2, 'mean_premium': 59.2},
    '44-45': {'name': 'Retail Trade', 'relativity': 1.264, 'count': 65, 'mean_premium': 52.8},
    '51': {'name': 'Information & Technology', 'relativity': 1.231, 'count': 102, 'mean_premium': 51.4},
    '92': {'name': 'Public Administration', 'relativity': 1.221, 'count': 52, 'mean_premium': 51.0},
    '52': {'name': 'Finance & Insurance', 'relativity': 1.181, 'count': 106, 'mean_premium': 49.3},
    '31-33': {'name': 'Manufacturing', 'relativity': 1.023, 'count': 67, 'mean_premium': 42.7},
    '21': {'name': 'Mining, Quarrying, Oil & Gas', 'relativity': 0.955, 'count': 21, 'mean_premium': 39.9},
    '62': {'name': 'Health Care & Social Assistance', 'relativity': 0.914, 'count': 117, 'mean_premium': 38.1},
    '22': {'name': 'Utilities', 'relativity': 0.885, 'count': 38, 'mean_premium': 36.9},
    '42': {'name': 'Wholesale Trade', 'relativity': 0.804, 'count': 10, 'mean_premium': 33.6},
    '48-49': {'name': 'Transportation & Warehousing', 'relativity': 0.800, 'count': 23, 'mean_premium': 33.4},
    '11': {'name': 'Agriculture, Forestry & Fishing', 'relativity': 0.702, 'count': 4, 'mean_premium': 29.3},
    '72': {'name': 'Accommodation & Food Services', 'relativity': 0.690, 'count': 16, 'mean_premium': 28.8},
    '61': {'name': 'Educational Services', 'relativity': 0.663, 'count': 37, 'mean_premium': 27.7},
    '53': {'name': 'Real Estate & Rental', 'relativity': 0.663, 'count': 8, 'mean_premium': 27.7},
    '54': {'name': 'Professional Services', 'relativity': 0.650, 'count': 36, 'mean_premium': 27.1},
    '56': {'name': 'Administrative & Support', 'relativity': 0.620, 'count': 16, 'mean_premium': 25.9},
    '81': {'name': 'Other Services', 'relativity': 0.617, 'count': 3, 'mean_premium': 25.8},
    '71': {'name': 'Arts, Entertainment & Recreation', 'relativity': 0.615, 'count': 14, 'mean_premium': 25.7},
    '23': {'name': 'Construction', 'relativity': 0.598, 'count': 13, 'mean_premium': 25.0},
}

industry_df = pd.DataFrame([
    {'Code': k, 'Industry': v['name'], 'Relativity': v['relativity'], 'Mean Premium ($M)': v['mean_premium'], 'Count': v['count']}
    for k, v in INDUSTRY_DATA.items()
]).sort_values('Relativity', ascending=False)

print(f'✓ Supported Industries: {len(INDUSTRY_DATA)}')
print(f'✓ Total Companies Analyzed: 750')
print('\nIndustry Summary:')
print(industry_df.to_string(index=False))

"""## 5. Premium Calculation Functions"""

def calculate_gross_premium(company_revenue: float, industry_code: str) -> Dict:
    """Calculate insurance premium using industry relativity"""
    if industry_code not in INDUSTRY_DATA:
        raise ValueError(f'Unknown industry: {industry_code}')

    # Base premium calculation using relativity
    relativity = INDUSTRY_DATA[industry_code]['relativity']

    # Mean premium from $41.8M average (adjusted for revenue)
    # Use relativity as multiplier
    base_rate = (ACTUARIAL.mean_final_premium / 1000) * relativity  # Convert to percentage

    # Pure premium before loadings
    pure_premium_rate = base_rate / (1 + ACTUARIAL.total_loading_pct)

    pure_premium_usd = company_revenue * pure_premium_rate
    gross_premium_usd = company_revenue * base_rate

    return {
        'pure_premium_rate': pure_premium_rate,
        'gross_premium_rate': base_rate,
        'pure_premium_usd': pure_premium_usd,
        'gross_premium_usd': gross_premium_usd,
        'industry_relativity': relativity,
        'loading_pct': ACTUARIAL.total_loading_pct,
    }

def calculate_proportional_reinsurance(gross_premium: float) -> Dict:
    """Calculate Proportional Reinsurance (Quota Share + Surplus)"""
    quota_gross = gross_premium * ACTUARIAL.quota_share_pct
    quota_commission = quota_gross * ACTUARIAL.quota_share_commission
    quota_net = quota_gross - quota_commission

    surplus_gross = gross_premium * ACTUARIAL.surplus_share_pct
    surplus_commission = surplus_gross * ACTUARIAL.surplus_commission
    surplus_net = surplus_gross - surplus_commission

    return {
        'quota_share': {'gross': quota_gross, 'commission': quota_commission, 'net': quota_net},
        'surplus_share': {'gross': surplus_gross, 'commission': surplus_commission, 'net': surplus_net},
        'total_gross': quota_gross + surplus_gross,
        'total_net': quota_net + surplus_net,
    }

def calculate_xol_reinsurance(gross_premium: float) -> Dict:
    """Calculate Excess of Loss (3-layer tower)"""
    layer1_loss = gross_premium * 0.08
    layer1_premium = layer1_loss * ACTUARIAL.xol_profit_loading

    layer2_loss = gross_premium * 0.012
    layer2_premium = layer2_loss * ACTUARIAL.xol_profit_loading

    layer3_loss = gross_premium * 0.0008
    layer3_premium = layer3_loss * ACTUARIAL.xol_profit_loading

    return {
        'layer1': {'limit': 50000000, 'premium': layer1_premium, 'rol': (layer1_premium/gross_premium)*100},
        'layer2': {'limit': 100000000, 'premium': layer2_premium, 'rol': (layer2_premium/gross_premium)*100},
        'layer3': {'limit': 150000000, 'premium': layer3_premium, 'rol': (layer3_premium/gross_premium)*100},
        'total_premium': layer1_premium + layer2_premium + layer3_premium,
    }

print('✓ Calculation functions defined')

"""## 6. Agent Tool: Reinsurance Quotation

Complete quotation tool with sample response generation
"""

def quotation_tool(company_name: str, company_revenue_usd: float, industry_code: str) -> str:
    """Generate complete reinsurance quote"""
    try:
        if company_revenue_usd < 100000000:
            return f'Error: Minimum revenue is $100M. Received: ${company_revenue_usd:,.0f}'
        if industry_code not in INDUSTRY_DATA:
            return f'Error: Unknown industry {industry_code}. Supported: {list(INDUSTRY_DATA.keys())}'

        insurance = calculate_gross_premium(company_revenue_usd, industry_code)
        proportional = calculate_proportional_reinsurance(insurance['gross_premium_usd'])
        xol = calculate_xol_reinsurance(insurance['gross_premium_usd'])

        result = f"""
╔════════════════════════════════════════════════════════════════════╗
║                   REINSURANCE QUOTATION                            ║
╚════════════════════════════════════════════════════════════════════╝

COMPANY INFORMATION:
  Company Name: {company_name}
  Annual Revenue: ${company_revenue_usd:,.0f}
  Industry: {INDUSTRY_DATA[industry_code]['name']} (Code: {industry_code})
  Industry Relativity: {insurance['industry_relativity']:.3f}x

PRIMARY INSURANCE PREMIUM:
  Gross Premium Rate: {insurance['gross_premium_rate']*100:.2f}%
  Loading Factors: {insurance['loading_pct']*100:.0f}% (Acq 20%, Admin 10%, Profit 15%, Uncertainty 8%, Reinsurance 5%)
  Annual Premium: ${insurance['gross_premium_usd']:,.0f}

OPTION 1: PROPORTIONAL REINSURANCE
  Quota Share (30%):
    Gross Premium: ${proportional['quota_share']['gross']:,.0f}
    Commission (30%): ${proportional['quota_share']['commission']:,.0f}
    Net Reinsurer Cost: ${proportional['quota_share']['net']:,.0f}

  Surplus Share (15%):
    Gross Premium: ${proportional['surplus_share']['gross']:,.0f}
    Commission (30%): ${proportional['surplus_share']['commission']:,.0f}
    Net Reinsurer Cost: ${proportional['surplus_share']['net']:,.0f}

  ► TOTAL PROPORTIONAL NET: ${proportional['total_net']:,.0f}

OPTION 2: EXCESS OF LOSS (3-LAYER TOWER)
  Layer 1 (0 xs $50M):
    Premium: ${xol['layer1']['premium']:,.0f} ({xol['layer1']['rol']:.2f}% ROL)

  Layer 2 ($50M xs $100M):
    Premium: ${xol['layer2']['premium']:,.0f} ({xol['layer2']['rol']:.2f}% ROL)

  Layer 3 ($150M xs $150M):
    Premium: ${xol['layer3']['premium']:,.0f} ({xol['layer3']['rol']:.2f}% ROL)

  ► TOTAL XOL PREMIUM: ${xol['total_premium']:,.0f}

✨ RECOMMENDED: HYBRID STRUCTURE
  Proportional Core: ${proportional['total_net']:,.0f}
  XOL Layer 3 Tail: ${xol['layer3']['premium']:,.0f}
  ► TOTAL ANNUAL COST: ${proportional['total_net'] + xol['layer3']['premium']:,.0f}

RATIONALE:
  • Hybrid combines frequency protection (proportional) with catastrophic tail (XOL)
  • Optimal capital efficiency for reinsurer
  • Based on analysis of 750 companies across 20 industries
"""
        return result
    except Exception as e:
        return f'Error: {str(e)}'


# ===== SAMPLE RESPONSE GENERATION =====
print('\n' + '='*75)
print('SAMPLE RESPONSE GENERATION')
print('='*75)
sample_quote = quotation_tool('Sample Tech Corp', 5000000000, '51')
print(sample_quote)
print('\n✓ Sample generation successful - Agent tool is operational!')

"""## 7. Create the Quotation Agent"""

quotation_agent = Agent(
    name='Cyber Risk Quotation Agent',
    model=Gemini(id='gemini-2.5-flash'),
    tools=[quotation_tool],
    description='Generates insurance and reinsurance quotes for cyber/AI risk',
    instructions=f'''You are an insurance actuarial agent specializing in cyber and AI risk pricing.

CAPABILITIES:
- Generate comprehensive insurance and reinsurance quotes
- Compare Proportional vs Excess of Loss structures
- Provide recommendations based on company profile
- Explain actuarial assumptions and methodology

SUPPORTED INDUSTRIES (NAICS Codes):
{json.dumps({k: v['name'] for k, v in INDUSTRY_DATA.items()}, indent=2)}

GUIDELINES:
- Minimum revenue: $100 million
- Always use quotation_tool for quotes
- Recommend Hybrid (Proportional + XOL) for most cases
- Data based on 750 companies analyzed from complete_pricing_framework.xlsx
- Be professional and data-driven''',
    markdown=True,
)

print('✓ Agent created successfully')
print(f'  Model: {quotation_agent.model.id}')
print(f'  Industries: {len(INDUSTRY_DATA)} supported')
print(f'  Status: Ready (requires Google API key)')

"""## 8. Example Queries"""

EXAMPLE_QUERIES = [
    # 'Generate a reinsurance quote for TechCorp with $5B revenue in Technology (51)',
    # 'Compare proportional and XOL for FinanceGlobal, $3B revenue, Finance industry (52)',
    # 'Generate quotes for three companies: Tech $5B (51), Finance $3B (52), Healthcare $8B (62)',
    'What would hybrid reinsurance cost for a $1.5B retail company (44-45)?'
]

print('Example agent queries:')
for i, q in enumerate(EXAMPLE_QUERIES, 1):
    print(f'{i}. {q}')
    # time.sleep(4)
    response = quotation_agent.run(q)
    print(response.content)

"""## 9. Interactive Usage (Requires Google API Key)"""

# Setup steps:
# 1. Get key from https://makersuite.google.com/
# 2. Set environment: os.environ['GOOGLE_API_KEY'] = 'your-key-here'
# 3. Uncomment and run below:

# response = quotation_agent.run(
#     'Generate quote for TechCorp, $5B revenue, Technology (51)'
# )
# print(response)

"""## 10. Batch Processing"""

def batch_quotation(companies: list) -> pd.DataFrame:
    """Process multiple companies at once"""
    results = []
    for company in companies:
        try:
            ins = calculate_gross_premium(company['revenue'], company['code'])
            prop = calculate_proportional_reinsurance(ins['gross_premium_usd'])
            xol = calculate_xol_reinsurance(ins['gross_premium_usd'])
            hybrid = prop['total_net'] + xol['layer3']['premium']

            results.append({
                'Company': company['name'],
                'Revenue ($B)': company['revenue']/1e9,
                'Insurance ($M)': ins['gross_premium_usd']/1e6,
                'Proportional ($M)': prop['total_net']/1e6,
                'XOL ($M)': xol['total_premium']/1e6,
                'Hybrid ($M)': hybrid/1e6,
            })
        except Exception as e:
            print(f'Error processing {company["name"]}: {e}')
    return pd.DataFrame(results)

# Test batch processing
test_companies = [
    {'name': 'TechCorp Inc', 'revenue': 5000000000, 'code': '51'},
    {'name': 'FinanceGlobal', 'revenue': 3000000000, 'code': '52'},
    {'name': 'RetailMax Co', 'revenue': 2000000000, 'code': '44-45'},
    {'name': 'Healthcare Plus', 'revenue': 8000000000, 'code': '62'},
]

batch_results = batch_quotation(test_companies)
print('\nBatch Quote Results:')
print(batch_results.to_string(index=False))

"""## 11. Summary & Status

**Data Source:** complete_pricing_framework.xlsx (750 companies, 20 industries)

**Features:**
- Industry-specific relativity multipliers (0.598 - 1.417x)
- 58% total loading factors (Acquisition, Admin, Profit, Uncertainty, Reinsurance)
- Proportional and XOL reinsurance pricing
- Hybrid structure recommendation
- Agno agent with Google Gemini
- Batch processing capability

**Status:** ✅ Production Ready

"""

"""## 12. UI For Streamlit Deployment """

import streamlit as st
import os
import json
from agno.agent import Agent
# Import your specific agent configuration from your backend script
# Adjust the import statement below depending on how your agent is named in cyber_ai_reinsurance_quotation_agent.py
try:
    from cyber_ai_reinsurance_quotation_agent import reinsurance_agent # Example agent instance name
except ImportError:
    # Fallback/Placeholder if importing directly needs to be initialized here
    reinsurance_agent = None

# 1. Page Configuration & Styling
st.set_page_config(
    page_title="Cyber & AI Risk Reinsurance Pricing Chatbot",
    page_icon="🤖",
    layout="wide"
)

st.title("🌐 Cyber & AI Reinsurance Quotation Agent")
st.markdown("Interact with the actuarial AI agent to dynamically price risk layers, generate reinsurance quotes, and compare structures.")

# 2. Secure API Key Management via Streamlit Secrets
if "GOOGLE_API_KEY" not in os.environ:
    if "GEMINI_API_KEY" in st.secrets:
        os.environ["GOOGLE_API_KEY"] = st.secrets["GEMINI_API_KEY"]
    elif "GOOGLE_API_KEY" in st.secrets:
        os.environ["GOOGLE_API_KEY"] = st.secrets["GOOGLE_API_KEY"]
    else:
        st.warning("⚠️ GOOGLE_API_KEY not detected. Please add it to your `.streamlit/secrets.toml` file.")

# 3. Initialize Chat History in Session State
if "messages" not in st.session_state:
    st.session_state.messages = [
        {"role": "assistant", "content": "Hello! I am your Reinsurance Quotation Agent. Ask me to generate a quote or analyze risk profiles (e.g., *'Generate a reinsurance quote for TechCorp with $5B revenue in Technology'*)."}
    ]

# Display historical messages from session state
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

# 4. Handle User Inputs & Agent Execution
if user_query := st.chat_input("Type your underwriting or reinsurance pricing request here..."):
    
    # Render user message
    st.session_state.messages.append({"role": "user", "content": user_query})
    with st.chat_message("user"):
        st.markdown(user_query)

    # Generate agent response container
    with st.chat_message("assistant"):
        response_placeholder = st.empty()
        
        with st.spinner("Actuarial agent analyzing metrics and simulating loss costs..."):
            try:
                # If the agent is imported, invoke its run method
                if reinsurance_agent is not None:
                    # Capture the agent's response stream or text run
                    agent_response = reinsurance_agent.run(user_query)
                    output_text = agent_response.content if hasattr(agent_response, 'content') else str(agent_response)
                else:
                    # Backup fallback explanation if it needs to be run inline
                    output_text = f"#### Mock Output for: '{user_query}'\n\n*Backend script recognized. Ensure `reinsurance_agent` is correctly exposed for automated parsing.*"
                
                # Format the structured markdown response dynamically
                response_placeholder.markdown(output_text)
                
                # Save to session history
                st.session_state.messages.append({"role": "assistant", "content": output_text})
                
            except Exception as e:
                error_msg = f"❌ **Error running pricing model:** {str(e)}"
                response_placeholder.error(error_msg)
                st.session_state.messages.append({"role": "assistant", "content": error_msg})
