GOOGLE_API_KEY = "AQ.Ab8RN6LJnmBzDvGTj2mqh_Ov1EgAEK2tDHW3_8VYFHBy3Stoxg"
Capstone_Project = "AQ.Ab8RN6JGMMTw4Iqe7T8uH13z90OfKzBHv56mlZFqyT7euN1A1Q"
Actuarial_project = "AQ.Ab8RN6KhddnZezey05kBZ4yPp2E6PBS3WaNwExhNoZVZA2HfWw"
Final_Project_Key = "AQ.Ab8RN6LNbN9QhSKo_LOYq2rpM0ya-0S8EWTM2b7uG8juVhoSuQ"
